"""Added backImg to QABoard

Revision ID: b192d235133d
Revises: 
Create Date: 2021-12-19 20:47:23.342512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b192d235133d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qa_board', sa.Column('backImg', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qa_board', 'backImg')
    # ### end Alembic commands ###
